# try:
#     print(greeting)
# except:
#     print("A problem occurred")

# greeting = "Hello"

# try:
#     print(greeting)
# except:
#     print("A problem occurred")
# else:
#     print("The code worked without a problem")


# greeting = "Hello"

# try:
#     print(greeting)
# except:
#     print("A problem occurred")
# else:
#     print("The code worked without a problem")
# finally:
#     print("Your exception handling is complete")

friend = "Taj"

try:
  print(brother)
except:
  print("A problem occurred") 
else:
  print("The code worked without a problem")
finally:
  print("Error handling is complete")